# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: |
         sudo rm -rf .mozilla
         sudo rm -rf /opt/firefox/*
         sudo apt-get remove --purge firefox
         sudo updatedb
         locate firefox
         wget https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_57.0-0ubuntu1_amd64.deb
         sudo dpkg -i firefox-mozilla-build_57.0-0ubuntu1_amd64.deb
         sudo unlink /usr/bin/firefox
         sudo ln -s /opt/firefox/firefox /usr/bin/firefox

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mkdir test-reports

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean integration-test
